services:
  postgres:
    image: postgres:16-alpine
    container_name: ddd-nest-api-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456xX
      POSTGRES_DB: dev_cms_ultimate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d dev_cms_ultimate']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
